export const ApiPaths = {
  login: `/login`,
  register: `/register`,
  registerfield: "/registerfields",
  checkSponsor: `/check_username`,
  getProfile: `/get_profile`,
  getWallets: `/get_wallets`,
  changePassword: `/update-password`,
  updateProfile: `/update-profile`,
  paymentRequest: "/payment-request",
  getPaymentMethod: "/get-payment-method",
  getPaymentTransaction: `/get-payment-transaction`,
  topUp: `/topup`,
  getTeams: `/get_team_section`,
  withdraw: "/withdraw",
  getPackages: "/get-all-package",
  getLevels: "/get_level_team",
  getOrders: "/get_orders",
  getRanks: "/get-ranks",
  getALlTeam: "/get_all_team",
  generationTree: "/get_genealogy_tree",
  claimReward: "/claim_reward",
  getBankDetails: "/submit-bank-kyc",
  getPanCardDetails: "/submit-pan-kyc",
  getAddressDetails: "/submit-address-kyc",
  bonanzaData: "/get-bonanza",
  updateBankDetails: "/get_bank_details",
  getSip:"/getSips",
  payInstallment:"/payinstallment",
  getCompanyDetails: "/get-company-info",
  getKycStatus:"/check-kyc",
  p2pTransfer:"/fund_transfer",
  forgotPassword:"/forgot-password",
  sendOtp:"/send-otp"
};
